---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-credentials
  namespace: teleport-dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  refreshInterval: 1h
  target:
    name: harbor-registry-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"repos.eu-central-1.myidp.cloud":{"username":"admin","password":"{{ .password }}","auth":"{{ printf "admin:%s" .password | b64enc }}"}}}
  data:
    - secretKey: password
      remoteRef:
        key: harbor/admin
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
