---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport-dev-home
  namespace: teleport-dev
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 10Gi
